### ISSUE TITLE
Microdungeons not spawning. 

### ISSUE THREAD

**Issue by Fevix** [Fevix/Avali#1]

**Comment by CrispyBlockland** [comment]
Error: Failed to place microdungeon (MapException) Key 'avali1' not found in Map::get()
This error found in the log may be related.

**Comment by Fevix** [comment]
That's the error the issue is talking about. 
There's something wrong with the dungeons but I can't pinpoint it.

**Comment by Luthor614** [comment]
Hey Fevix, I've started work on your biome patched for the micro dungeons :) got em' almost working but now am running into this error: 

[13:09:10.926] Error: Failed to process dungeon file /dungeons/microdungeons/randomencounter/avali/avalirandom.dungeon : (JsonException) Improper conversion to JsonObject from string

Here's where I'm at so far...

https://www.dropbox.com/s/vl8vjlk2b37olfn/biomes.7z?dl=0
https://www.dropbox.com/s/bumtjqo8t14yh76/dungeons.7z?dl=0

Maybe someone could take a look cuz I'm stumped! Threw the dungeon file into a JSON validator and came back valid...

**Comment by Luthor614** [comment]
Sorry, fiddled with the random encounter name a little just to identify it easily.

**Comment by thakyZ** [comment]
I'll take a look at it for Fevix

**Comment by Luthor614** [comment]
Nailed it!!! There was a comma missing down the line

https://www.dropbox.com/s/zsabhiv7i4b9bbn/avalirandom.dungeon?dl=0

Log file shows no errors :) 
https://www.dropbox.com/s/zheic9bey0ky018/starbound.log?dl=0

**Comment by thakyZ** [comment]
Would you like to make the patch or do you want me to do the patch?

**Comment by Luthor614** [comment]
Patch is already done, was posted above :) just drop the biomes file into the master folder, same as the dungeons folder, and then update the dungeon file with the last one.
https://www.dropbox.com/s/vl8vjlk2b37olfn/biomes.7z?dl=0
https://www.dropbox.com/s/bumtjqo8t14yh76/dungeons.7z?dl=0
https://www.dropbox.com/s/zsabhiv7i4b9bbn/avalirandom.dungeon?dl=0

My log is clear of errors and am just testing it out now :)

**Comment by thakyZ** [comment]
IK but a patch to the actual code

**Comment by Luthor614** [comment]
Does the code need a patch? Microdungeons are patched via the required biome files, which have already done, and the dungeon file is also done (just added a comma and checked the stats).

**Comment by thakyZ** [comment]
No I mean add your files to the repo

**Comment by Luthor614** [comment]
DERP!!! That's what you meant :) gimme few mins of testing and will let ya know.

**Comment by Fevix** [comment]
Someone make a pull request and Thaky can pull.

**Comment by thakyZ** [comment]
Fevix you should close this issue when pulled.

**Comment by Fevix** [comment]
Will do.

**Comment by Luthor614** [comment]
![image](https://cloud.githubusercontent.com/assets/12685707/7903535/6e0676a6-07ad-11e5-83fd-d9fd9ad23eb6.png)

Success !!! Check out ma grave site :)

**Comment by Luthor614** [comment]
![image](https://cloud.githubusercontent.com/assets/12685707/7903539/b373bc58-07ad-11e5-9e7d-5972d4436c16.png)

**Comment by thakyZ** [comment]
Are you creating the pull request @Luthor614 or should I?

**Comment by Luthor614** [comment]
PULL request away!!!

**Comment by thakyZ** [comment]
Ok, first thing is to test if they can be placed underground

**Comment by Luthor614** [comment]
Who's the man?

**Comment by Fevix** [comment]
You da man
