### ISSUE TITLE
Agaran speech lines

### ISSUE THREAD

**Issue by Fevix** [Fevix/Avali#10]
Agarans ingame use Floran speech lines, appearing to be using their Avian lines. 

Pertinent files are: 
npc/shroomguard.npctype
npc/shroommerchant.npctype

.patch files should be created. There's a translation page somewhere for the agarans, use that instead of typing random gibberish. 

Edit: Translations: http://community.playstarbound.com/threads/someone-feel-like-helping-me-with-the-translation-of-the-aragan-language.68824/page-2

**Comment by thakyZ** [comment]
I would like to know how this affects the Avali?

**Comment by Fevix** [comment]
It's a cosmetic change. 
It's not critical, just something it'd be nice to have.

**Comment by Fevix** [comment]
Merged to #15
