### ISSUE TITLE
wrong name research station icon

### ISSUE THREAD

**Issue by RaikaSiray** [Fevix/Avali#117]
https://github.com/Fevix/Avali/blob/master/objects/ship/avaliresearchstation/researchstationicon.png
https://github.com/Fevix/Avali/blob/master/objects/ship/avaliresearchstation/avaliresearchstation.object#L41
avaliresearchstationicon.png is not found.
plz rename researchstationicon.png to avaliresearchstationicon.png!

**Comment by Fevix** [comment]
Good eyes
