### ISSUE TITLE
avalibandit.npctype loading crash

### ISSUE THREAD

**Issue by bathysophical** [Fevix/Avali#127]
Hey!! Just installed the newest update and received this error with a crash at launch:
"Fatal Exception caught: (StarException) An error occurred during loading: (NpcException) Error loading npc type '/avali-2.4.0/npcs/avalibandit.npctype'
Caused by: (NpcException) Repeat npc type name 'avalibandit'"

**Comment by Fevix** [comment]
Fix: Delete and reinstall.
Reason: You broke the cardinal rule for updating Avali mods, and that is to always, ALWAYS delete old versions before installing new versions. Any renames or removals will cause issues if you just install over.
