### ISSUE TITLE
It won't appear in the character creator

### ISSUE THREAD

**Issue by LazyByDefault** [Fevix/Avali#131]
As the title says. I'm using the ODB2 Character Creation Mod.

**Comment by Fevix** [comment]
starbound.log please.

**Comment by sfiuren** [comment]
I've had the same issue and its absolutely infuriating. Please help, I would be forever in your debt. 
[starbound.log.txt](https://github.com/Fevix/Avali/files/120663/starbound.log.txt)

**Comment by Fevix** [comment]
@sfiuren Install the mod correctly. The "avali.modinfo" file should be inside a folder in "mods". 
Like so: 
Giraffe_storage
|-mods
||-avali
|||-avali.modinfo
|||-animations folder
|||-items folder
|||-etc.,

**Comment by sfiuren** [comment]
I'm away from my computer but I'll look into it. While I was perusing the mod folder, I don't know if I saw the avali.modinfo, however I'm not 100% sure. I really do appreciate the speedy response, thank you.
