### ISSUE TITLE
Mod isn't recognized

### ISSUE THREAD

**Issue by RustyGentleman** [Fevix/Avali#132]
As it says in the title, the game doesn't recognize the mod at all. Doesn't even load it, from what I read in the log. I did install everything correctly, even checked .patch files to see if something was missing for some reason. (I was using other mods too, and most [apart from one, which is the same case as this] were working fine, but uninstalled them in the troubleshooting process.)

Sorry to bother, but I really have no idea why this is happening.

Log is as follows.
[starbound.txt](https://github.com/Fevix/Avali/files/106343/starbound.txt)

**Comment by Fevix** [comment]
Did you make sure avali.modinfo was in "/mods/avali/" and not something like "/mods/avali/avali/"?

**Comment by RustyGentleman** [comment]
I actually opened up the folder and dumped the contents in the mod folder, instead of extracting the whole folder.

**Comment by Fevix** [comment]
Alright. Next time you resolve an issue on your own, please update the ticket before just closing.
