### ISSUE TITLE
Talking to NPC kills them

### ISSUE THREAD

**Issue by Gallerga** [Fevix/Avali#136]
On using the action button to talk to an non hostile npc on a planet they die.
Below is an excerpt from my log
[20:05:39.961] Error: Exception while invoking lua function 'update'. (LuaException) Error code 2, [string "/scripts/behavior.lua"]:116: [dynamic]:3
[string "/scripts/behavior.lua"]:256: {converse}
[string "/scripts/behavior.lua"]:116: [sequence]:3
[string "/scripts/behavior.lua"]:212: [sayToEntity] error:
[string "/scripts/actions/dialog.lua"]:4: (AssetException) Error loading asset /dialog/converse.config:converse

**Comment by Fevix** [comment]
Possibly fixed by #138
Please test.

**Comment by Fevix** [comment]
Assumed fixed. Please reopen if not fixed.
