### ISSUE TITLE
universe_server.config.patch, should call avali not avain.

### ISSUE THREAD

**Issue by graycatgrayhat** [Fevix/Avali#14]
I noticed well inspecting the "Avali Frigate" ship posted by Ancev Caine.

File in question:  universe_server.config.patch

It is call for these, 

aviant0.structure
aviant1.structure
aviant2.structure
aviant3.structure
aviant4.structure
aviant5.structure
aviant6.structure
aviant7.structure
aviant8.structure

Which does and will work fine but they should be calling for these,

avali0.structure
avali1.structure
avali2.structure
avali3.structure
avali4.structure
avali5.structure
avali6.structure
avali7.structure
avali8.structure

Really this is just for the sake of clean file structure and naming, also the ship files them selves would also then need renamed.

This does not effect the mod in anyway and should be considered a "when we have the time type bug"

**Comment by Fevix** [comment]
I'm reasonably sure renaming the ships like that would break all current characters, as they all currently have in (I think) Metadata a line pointing to the current shipworld file which, currently, is "aviant_.structure". If it can't find that, it crashes.

**Comment by graycatgrayhat** [comment]
Ahh very very true XD that was my oversight, it would cause problems for them.
