### ISSUE TITLE
Sniper primary fire error

### ISSUE THREAD

**Issue by KaleShiba** [Fevix/Avali#143]
Error: could not load image asset 'animations/snipermuzzle/snipermuzzle.png: (insert x.x number here)   Been doing this for MULTIPLE updates...any clue what's up?  I down load the files and everything correctly...its just giving me that error when I fire the primary fire

**Comment by Fevix** [comment]
I've looked into it, myself, but couldn't find anything. Perhaps @Devani1 or @thakyZ can find something.

Course, constant Starbound updates have burned the entire team out, so I wouldn't expect anything out too fast.

**Comment by KaleShiba** [comment]
Perhpas its a issue of 'my computer is special' possibly.  I can understand the frustrating burn out though.

**Comment by Fevix** [comment]
No, this is constant, has been through all updates. From what I've been able to tell, it only affects the log file, though, and doesn't cause a crash, so it's so far on the backburner that unless one of us has a eureka moment, it's not happening.

**Comment by KaleShiba** [comment]
I physically don't see the shot in my case.  but its one of those 'what can you do' moments honestly.  It doesn't crash thwe game, and its not like I can't just predict where my shot goes anyway. Snipers are nice like that.

**Comment by Fevix** [comment]
My thoughts exactly

**Comment by Fevix** [comment]
Closing because it's inconsequential. it does not affect the game, it only affects the log
