### ISSUE TITLE
Mod Crashes Upon Startup

### ISSUE THREAD

**Issue by AreoAnts** [Fevix/Avali#145]
Every time I try to start up the mod, the game crashes, and this is the message that comes up. Is there any way to fix this?

![bug things](https://cloud.githubusercontent.com/assets/18638344/14765475/3f42d330-09b1-11e6-9a59-18340507f03e.png)

**Comment by Fevix** [comment]
@devani @thakyz suggest removal of spawner above in favor of the new tenant system. Cannot make commit myself. Please reference this issue in your commit

**Comment by Fevix** [comment]
Edit: cannot make commit due to being on mobile

**Comment by AreoAnts** [comment]
What do you mean by "removal of spawner above in favor of the new tenant system", exactly?

**Comment by Fevix** [comment]
There's a tenant system in vanilla Starbound that is much better than the spawner system. You can build their houses furnish them and place a colony deed inside the house and it will spawn a tenant for you. These tenants can give you gifts every now and then and you don't even have to do much to them

**Comment by Fevix** [comment]
What I meant by removal was completely deleting the spawner files included in the mod

**Comment by Fevix** [comment]
Fixed in b464829
