### ISSUE TITLE
Current list of Suggestions

### ISSUE THREAD

**Issue by Fevix** [Fevix/Avali#15]
Please reply to this "Issue" if you begin working on any of the following:

###### --Agaran Speech Lines
Nobody is working on this yet.
See #10 for more information, including pertinent files and a page with rough translations of Agaran speech  
  
  
###### --Axes, requested by Resonat
Nobody is working on this yet  
  
  
###### --Mystery Star nanoskin graphic
Nobody is working on this yet.  
  

###### --Codex
Nobody is working on this yet.  
  
  
###### --Rocket/Grenade Launchers
Nobody is working on this yet.

**Comment by Luthor614** [comment]
We need a bloody pet, that's what we need! lol

**Comment by Fevix** [comment]
A pet is in the works.

**Comment by Luthor614** [comment]
Ooooooohh me likey :) AND saves me the trouble of coming up with one on my
own lol. I just wanted  a recolored orbis pet for simplicities sake lol.

**Comment by Fevix** [comment]
Just a small reminder that this is a thing. Most of the above have been requested by players.

**Comment by Fevix** [comment]
Because this issue's description is simply a mess, I've thrown together a Trello. Please contact me on the forums if you'd like to participate (I literally did all of that Trello stuff in like 2 minutes, the interface is incredibly intuitive.)

Link: https://trello.com/b/gXXkQ3Lw/avali-starbound
