### ISSUE TITLE
Invisible/Indestructable Blocks Above Ship Teleporter

### ISSUE THREAD

**Issue by Etaleanic** [Fevix/Avali#151]
Not sure if this is intentional or not, but it seems quite inconvenient both for building in the ship and moving up/down that area leading up to the top room. [Image](http://prntscr.com/btm9dr)

**Comment by Fevix** [comment]
According to @Devani1 this looks like a teleporter design flaw. I'll look into it.

**Comment by Fevix** [comment]
It seems all vanilla teleporters have been changed from a floor pad to a full-height teleporter.

**Comment by Fevix** [comment]
Attempted fix added, please try again.

**Comment by Etaleanic** [comment]
Seems to be working now, though I had to swap the universe.server.config.patch files to use this version of the ship.
