### ISSUE TITLE
Items that used to require Steel should now use Tungsten instead...

### ISSUE THREAD

**Issue by Febilian** [Fevix/Avali#153]
The result being that many Avali guns and whatnot are currently crafted using Perfectly Generic Items, because steel is no longer existent.

EDIT: Other materials may also be missing/nonexistent, but I'm not sure which ones. Several items that are probably beyond steel equivalent are also utilizing PGIs in their crafting.

**Comment by Febilian** [comment]
Oops. Never mind this is known.

**Comment by Fevix** [comment]
Known issue, being worked on

**Comment by Fevix** [comment]
Possibly fixed, many recipes were updated. Please check again and close this issue if no further recipes are found.

**Comment by Febilian** [comment]
Unfortunately I uninstalled the mod after needing to stabilize the play environment with a friend, someone else may need to test this in the meantime. Apologies for the inconvenience.

**Comment by Fevix** [comment]
Checked out.
