### ISSUE TITLE
New ship licenses immediately unlocked once ship is fixed

### ISSUE THREAD

**Issue by Febilian** [Fevix/Avali#154]
I don't have a crew at all. Out of curiosity I accepted the first upgrade quest and turned it in, but then I immediately got the NEXT one upon entering my newly-upgraded ship next.

I don't think this is intended.

**Comment by Fevix** [comment]
Thanks for the report, but this is a low-priority issue. We're focusing more on making everything functional ingame, then we'll fix bugs like this.

**Comment by Febilian** [comment]
A bug is a bug. I was just reporting an issue I found, not demanding it be immediately fixed. I hope that's not a problem.

**Comment by Fevix** [comment]
Of course, not a problem. I just try to give acknowledgement to all reports as soon as I see them.

**Comment by Fevix** [comment]
Attempted fix by @SamuraiScientist in 56bbd2d358ce7176c099e8813f0439f39ffa879e. Please download, and delete all files located in "\items\active\weapons\melee\tiered\hammer\" and '\items\active\weapons\melee\tiered\spear\" as these are currently causing CTD on startup (Being looked into).
