### ISSUE TITLE
Misc Wiring/Elevator Bugs

### ISSUE THREAD

**Issue by Etaleanic** [Fevix/Avali#157]
Several Avali objects are missing the wiring connections. This is has the greatest effect on Avali ship lights (Apex ship light also shown, can be turned on/off) and Avali elevators, which are made nonfunctional by this, since they cannot be triggered. The Avali consoles also do not have outputs.
A few objects have wiring connections that are slightly off from where you expect them to be. (plated door and tent door)
[Image](http://prntscr.com/bu2gsj) (I've moved SAIL for all my ship tiers, uncentered things bother me.)

Also, the Avali elevators have platforms that neither fit to the elevator track nor match their hitboxes. [Image](http://prntscr.com/bu2j6d) (that window bothered me slightly too.)

**Comment by Fevix** [comment]
Thank you for the report, this will be looked into once the mod is functional.

**Comment by Radixy** [comment]
+ 

Any ETA on when it will be fixed? :)

**Comment by Fevix** [comment]
ETA: "When it's done"

**Comment by Fevix** [comment]
Has been fixed over several days.
