### ISSUE TITLE
Items in Incorrect Inventory Tab

### ISSUE THREAD

**Issue by Etaleanic** [Fevix/Avali#159]
Several of the Avali items need to be updated to sort into the new inventory tabs that have been added. Currently I remember the food items (not seeds) and Avali Data Chits sorting into the default tab, while they should sort into food and materials (?) tab respectively.

**Comment by Fevix** [comment]
Thank you for the report, this will be looked into once the mod is functional.

**Comment by Fevix** [comment]
From the looks of things, the tabs have been removed from vanilla. We will be emulating this behavior.

**Comment by Fevix** [comment]
This issue will remain open. If any other similar issues are noticed, please add them to this issue.
