### ISSUE TITLE
NPC and various fixes for Unstable 

### ISSUE THREAD

**Issue by doopcat** [Fevix/Avali#17]
Hi, I'm new to github (so I don't really know how to go about this) but I've been playing Starbound for a while and I've done unpublished personal modifications. Some of the most recent changes to the Pleased Giraffe unstable version of the game were making it crash with the Avali mod running so I decided to try some fixes of my own. The majority of what was preventing the game from even launching with the mod appears to be related to changes to npcs and objects used on the initial ship map. Here's what I've done so far:

1) Updating the .npctype patches for friendlyguard, merchant, villager, and villageguard
2) Creating a merchantpools.config.patch for avali item lists on the merchant.npctype
3) Creating patches for npc dialog, specifically to the converse, flee, guard, and merchant .configs
4) Updating starting objects on the ship, namely avalishipdoorbroken, avalishiplockertier0, avaliteleportertier0, and brokenavalifuelhatch

It occurred to me that I should at least post that I'm doing this here since I figure I might see if anyone else is writing these fixes already. In testing so far the log no longer throws errors for these specific things I've fixed, and I've been able to connect to a localhost server and have gotten as far as the steel armor quest. This quest is broken because the avali items do not have the latest quest tags to be recognized by the quest but I believe I can fix this too (I only found this problem a few minutes ago). Aside from that I haven't ran into any other bugs that I think are connected to the avali mod yet, but I will say that there are bugs in the Outpost about "npcToyIsAvailable" actions and the health of all the npcs mysteriously falling a bit more every time I travel to that map. I will probably look through the other avali ship items to make sure that they aren't going to cause errors, but I was able to fix the ship the first time (the core fragments upgrade) and didn't encounter any immediate crashes or errors in the log file.

Personally I'm going to keep working on this because I want to, but I'm very willing to share these fixes and if I'm capable I could probably assist with others. Again, I'm not sure how github works yet so I am sorry if this is in the wrong place or not the right format, I'll figure it out eventually.

**Comment by Fevix** [comment]
Any progress?

**Comment by Luthor614** [comment]
Hey Fevix,

Just working out the ins-outs of GitHub for my desktop...I've started the npc changes already so once I'm finished work later today I'll revisit and try to finish them up and commit the changes.

**Comment by Fevix** [comment]
Alright, thanks for the update.

**Comment by Luthor614** [comment]
And btw, has doopcat added anything? I just kinda rushed head first in to this...

**Comment by Fevix** [comment]
Doopcat did not contribute anything, at least not that I noticed. I'm closing this issue because the NPCs have been updated.
