### ISSUE TITLE
Not sure what to call this...

### ISSUE THREAD

**Issue by KaleShiba** [Fevix/Avali#170]
KaleShibata from the steam page.  gonna copy the part thats not listed in the log file here in one half and the actual log file in the other.  Note I'm attempting to run a dedicated server so friends can join and all.

Login attempt failed error: mismatch between client and server and the override option is not set. Thats's with the default setting.

If I force the mismatch (which usually causes major problems because it means its lacking assets its not scanning for) 

now the error is with force mismatch while subscribed to this: 

[Error] UniverseServer: exception caught: <MapException> Key 'avali' not found in Map: : get<>
[0] 1450f7a
[1] 144fef8
[2] 15b0330
[3] 177f03c
[4] 17827f5
[5] 181102e
[6] 178fbe1
[7] 178da30
[8] 144d84d
[9] 768c338a BaseThreadInitThunk
[10] 77c79902 RtLInitializeExceptionChain
[11] 77c798d5 RtlInitializeExceptionChain

Thats the error it spams and won't let me log my own dedicated server.

Log file:

[starbound_server.txt](https://github.com/Fevix/Avali/files/379396/starbound_server.txt)

**Comment by Fevix** [comment]
Is the Avali mod installed on the server?

**Comment by KaleShiba** [comment]
I have NO CLUE what they changed to how that works. mind explaining how to actually install that on the server?  (considering it used to be a plug and play method before.

**Comment by Fevix** [comment]
I've no clue, I haven't messed with servers.

**Comment by KaleShiba** [comment]
Ok evidently the issue is they went back to the old metadata/pak file crap.

this means I'd need to learn that whole assinine process again, or the metadata file would need to be added in...I'm actually going to see if I can avoid making extra work since the forums one does not seem to have a metadata file...but the pak method might work.

**Comment by Fevix** [comment]
There is most definitely a .metadata file in the Avali mod.
