### ISSUE TITLE
Seems to be a bandit camp spawn

### ISSUE THREAD

**Issue by Konsetsuki** [Fevix/Avali#171]
[starbound.log.1.txt](https://github.com/Fevix/Avali/files/379462/starbound.log.1.txt)

**Comment by Fevix** [comment]
I thought I fixed this. Has your Starbound workshop updated recently?

**Comment by Konsetsuki** [comment]
Yeah I was playing with a friend, it updated in the middle of the game and
we presume that's what happened to it. It's working fine now as far as I
can tell.
