### ISSUE TITLE
Missing Weapons, slightly broken UI.

### ISSUE THREAD

**Issue by c0b4ltl1ghtn1ng** [Fevix/Avali#172]
All of the Avali Shorswords are missing from the crafting tables. 's pretty much it for that.

The UI's kinda broken when it comes to the racial crafting tables what with the crafting times now, but I'm sure that one is known.

**Comment by Fevix** [comment]
Shortswords are still in a .sword format, which has been phased completely out in favor of the .activeitem format. I haven't gotten around to changing them over. 

Fun fact: Daggers are the same way!

As for the UIs, this is a known issue, and will be fixed soon.

**Comment by Fevix** [comment]
These issues have been resolved
