### ISSUE TITLE
Lots of "Object avali[itemname] defined twice" errors in starbound.log

### ISSUE THREAD

**Issue by bsperan** [Fevix/Avali#173]
FYI: I'm using the Steam Workshop version.
I haven't actually created an Avali character yet. But I was alarmed by the number of errors I found in my starbound.log which appear to be related to the Avali. It shouldn't be throwing out errors like this. Granted, I have several mods installed (all Workshop). But that should not explain what it says that all these Avali items are "defined twice"...

One example:

> [Error] Object avalitier6daggerdisplay defined twice, second time from /objects/racks/frameddagger/avalitier6daggerdisplay.object
[04:43:44.717]

Q: Would the order I install Workshop mods make any difference? Are you aware of any conflicts with Frack'n Universe (which I have installed)?

Attached is my starbound.log.
[starbound.log.zip](https://github.com/Fevix/Avali/files/379482/starbound.log.zip)

**Comment by Fevix** [comment]
No, no conflicts known. I doubt FU would have added Avali objects. 

And all objects are only defined once. No clue what's going on here. (You can see the files in the mod right here on the Github, click on "Code" at the top)

**Comment by Fevix** [comment]
One thing I can suggest: Delete the mod and reinstall.

**Comment by Fevix** [comment]
Fixed in 5be91e2
