### ISSUE TITLE
Cooker and Culinary not work

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [Fevix/Avali#176]
Avali Cooker and Culinary Not work! Cooker not fry the meat or something,and in Culinary recipes staion missing,while in other tables they are!

**Comment by Fevix** [comment]
Avali Cooker and Avali Culinary Station are part of the now-outdated Avali Augments and Assortments mod. I will be working to bring this mod up to Starbound 1.0 in the coming weeks.
