### ISSUE TITLE
cant play as avali

### ISSUE THREAD

**Issue by savron1001** [Fevix/Avali#177]
i made my character but when i tried to start the game it didnt work it says client ship world has errored heres the log
[Starbound log.zip](https://github.com/Fevix/Avali/files/380082/Starbound.log.zip)

**Comment by Fevix** [comment]
Which ship were you using?

**Comment by savron1001** [comment]
I don't know what you mean I just got the mod not a ship for it

**Comment by savron1001** [comment]
Never mind I subscribed to an a avali ship mod and it works now thanks
