### ISSUE TITLE
No recipies in culinary station

### ISSUE THREAD

**Issue by ColorshyTheDull** [Fevix/Avali#179]
As the title states; the culinary station is not showing any recipes.
[starbound.log](https://github.com/Fevix/Avali/files/380217/starbound.txt)
Problem persisted after removal of UI editing mods.

**Comment by Fevix** [comment]
Known issue, the crafting stations will all be fixed in a coming patch. No ETA.

**Comment by Jeadbe** [comment]
Just noticed Frackin Universe has un-updated versions of the culinary station and such, so this problem may persist until that mod is updated.

**Comment by Fevix** [comment]
Has this issue been resolved?
