### ISSUE TITLE
(ItemException) No such item 'avaliclimbingaxe'

### ISSUE THREAD

**Issue by kley2101** [Fevix/Avali#183]
As the title says, i having this error every time i try to open the avali nanolathe.

**Comment by Zekrom805** [comment]
same, my other friends are not having this problem, i really want to be able to access everything in the mod.

**Comment by kley2101** [comment]
I have the add-on Avali Rocket launcher. I removed the add-on and the nanolathe worked. Is some error with the climbingaxe of that mod.

**Comment by Zekrom805** [comment]
Oh, I have the same thing to lel, thanks
