### ISSUE TITLE
Errors significantly slowing down server

### ISSUE THREAD

**Issue by check080** [Fevix/Avali#189]
There are two errors which slow down my server with the mod installed (manually, not workshop)

[Error] Could not apply patch from source: ../mods/Avali-master.  Caused by: (JsonPatchException) Could not apply patch to base. (JsonPatchException) Could not apply operation to base. (TraversalException) No such key 'weaponwarning2' in pathApply("/weaponwarning2/avali")

(and one previously reported)

[Error] Could not apply patch from source: ../mods/Avali-master.  Caused by: (JsonPatchException) Could not apply patch to base. (JsonPatchException) Could not apply operation to base. (TraversalException) No such key 'helpme' in pathApply("/helpme/avali")

It is possible the errors are not causing the slowdown, however the server ran fine before the mod was installed.

**Comment by Fevix** [comment]
Both of these are issues with the .npctype.patch files. I'm making this a priority if it's causing slowdown.

**Comment by Fevix** [comment]
Has this issue been alleviated?
