### ISSUE TITLE
Nanolathe problem

### ISSUE THREAD

**Issue by Xsenonn** [Fevix/Avali#194]
Hey, I'm having an issue with nanolathe, there's just no recipes in it (i guess), loom and gunbench are working, but lathe's empty.

**Comment by Jeadbe** [comment]
This is related to Issue #179 and may be caused by frackin universe: it contains copies of the Avali objects,  but they do not appear to be updated with Fevix's changes. Are you using the FU mod?

**Comment by neosapian6** [comment]
Jeadbe i am having the same issue as well, however it only started right about by the time im posting this, beforehand it was working absolutely fine, had all the recipes and everything. but now it just went poof... i guess ill have to wait or find the spawn id for the avali blocks and such so i can continue building what i was building.

**Comment by Fevix** [comment]
Newest update broke the nanolathe's GUI, but the recipes should still all be there.

**Comment by Fevix** [comment]
New update is out with fix.

**Comment by neosapian6** [comment]
ah, i see them now, thanks fevix ^.^!
