### ISSUE TITLE
NPC conversation files loading improperly

### ISSUE THREAD

**Issue by Bluulion** [Fevix/Avali#195]
It's been a while since I played Starbound, so I am not sure how much NPCs have changed or if the mod affects npc interaction or not, but npcs used to have unique dialogue depending on you character's species. So far almost none of them seem to acknowledge that my character is an Avali. Only the Mushroom people (who keep calling me fluffy) and one loyalist Apex noticed, and the rebel Apex think my Avali character is human. Sure it isn't game breaking, but I did read up that the mod used to have that same dialogue feature.

**Comment by Fevix** [comment]
This feature has been removed in vanilla, as far as I'm aware. All the lines are still active in the mod, it's just that they aren't being called on. I could be wrong, though, and if I am, I'll set about fixing it.

**Comment by Bluulion** [comment]
A line was called on that one time with the first apex npc, who called my character a raptor, but that could be a left over thing.

**Comment by Bluulion** [comment]
A line was called on that one time with the first apex npc, who called my character a raptor, and argarians (those mushroom people) still have the lines called on. I have just read about the generic responses, but it might be still possible to get the race specific ones again. If only I knew how to mod.

**Comment by Bluulion** [comment]
I'm looking at the files, and some npcs like the "cultist" or "devout avian" and the fenerox have race specific responses, but it seems like the villager responses are lumped up into files such as the converse.config and fight.config files, with lines in the default tag, such as:

"apex" : {
      "default" : [
        "Hello.",
        "How are you?",
        "How are you doing?",
        "Nice to meet you.",
        "I hope you are well, my friend.",
        "Big Ape is watching.",
        "I hope you have a pleasant day.",
        "It is good to see you.",
        "Can I help you?",
        "Good day, my friend.",
        "Hello, stranger.",
        "Welcome.",
        "Welcome, my friend.",
        "It is nice to meet you.",
        "Please, stay a while.",
        "How do you do, my friend?",
        "Greetings, stranger, and welcome.",
        "Hello, friend.",
        "How is it going?",
        "Have a good day.",
        "Can I offer you anything, my friend?",
        "Pleased to meet you, friend.",
        "Have a good day.",
        "Make yourself at home.",
        "Hi there.",
        "Hi.",
        "Ok, nice to meet you.",
        "Alright, my friend?",
        "Hey there, strange person.",
        "Hello to you."
      ]

**Comment by Fevix** [comment]
Thing is, we already HAVE lines added in for conversations like this.
https://github.com/Fevix/Avali/blob/master/dialog/converse.config.patch

**Comment by Bluulion** [comment]
Ah, your right, my bad. And I just noticed there are other race specific responses for villagers on the converse.config file. It might be that I haven't run into them yet, or there are too many generic responses that drown out the race specific ones.
