### ISSUE TITLE
Avali race MP error!

### ISSUE THREAD

**Issue by ZombieHunterCriss** [Fevix/Avali#196]
After some some trying to find out why the Avali race errors try to enter a Server/Friend it was when I was it in SP. It is the Teleporter it out of date and will not work in MP. Here are the link to the screenshot of starbounds teleporter and the Avali race teleporter

Starbound 1.0: http://steamcommunity.com/sharedfiles/filedetails/?id=731886042

Avali race: http://steamcommunity.com/sharedfiles/filedetails/?id=731886336

**Comment by Fevix** [comment]
Incorrect. I've played on servers with this version of the mod. The teleporters are not out of date, they are just a regular object (And can be any shape) that's set to open the teleporter dialogue when interacted with.
