### ISSUE TITLE
Error parsing StoredFunction descriptor

### ISSUE THREAD

**Issue by Devani1** [Fevix/Avali#20]
Error: Exception caught in client main-loop: (StoredFunctionException) Error parsing StoredFunction descriptor
Something to do with the Firelance. Can't figure it out...

**Comment by Fevix** [comment]
Look into the existing (vanilla) bow weapons, perhaps? The Firelance, to the engine, is a bow with high projectile speed and no arc.

I may look into it myself, but I've got to go somewhere and haven't unpacked the new assets.

**Comment by Devani1** [comment]
I have looked at the bow.gun file and the firelance file. I see there are some differences, but whatever I tried tweaking resulted in the same error.

**Comment by Fevix** [comment]
I more or less made the firelance files identical to the bow files. That seems to have worked.
