### ISSUE TITLE
Avali pickaxe, laser, chainsaw, and hoe missing from nanolathe

### ISSUE THREAD

**Issue by aztectornado** [Fevix/Avali#203]
The Avali Pickaxe, Laser, Chainsaw and Hoe are all missing from the nanolathe's menu in the current update. Probably a bug from the new UI update. The ones I already had made prior are still around in my inventory, but new ones cannot be made.

That said, the laser could probably do with a balance tweak; as it is, you only need coal and pixels to make a 4x4 rapid mining tool... Maybe you should include a single diamond as the focusing crystal, or something?

**Comment by Fevix** [comment]
All are now crafted in the second-tier farming table, just look through the tabs.

**Comment by aztectornado** [comment]
Ohh.... That makes more sense. Thanks for the quick reply!
