### ISSUE TITLE
Nanolathe not showing recipes

### ISSUE THREAD

**Issue by TuscanMadakaius** [Fevix/Avali#205]
The nanolathe in my game shows no recipes at all, just an empty display.

**Comment by Fevix** [comment]
Known issue, no known cause.

**Comment by Fevix** [comment]
What mods do you have installed?

**Comment by TuscanMadakaius** [comment]
xbawks, Gardenbots, XS Mechs and Modify Matter Manipulator

**Comment by Fevix** [comment]
No others?

**Comment by TuscanMadakaius** [comment]
Nope, just a lightly modded game. I was able to use the lathe in the beginning, but when I went to make some aeroponics tubes the next day it was gone completely from the lathe recipe list, as was everything else.

**Comment by Fevix** [comment]
Has this issue been resolved?

**Comment by TuscanMadakaius** [comment]
Yes, seems to be working fine now. Thanks heaps!
