### ISSUE TITLE
Protectorate Vanity Cloths Set

### ISSUE THREAD

**Issue by Dragon-Tom005** [Fevix/Avali#206]
After making my escape from the Human planet Earth, I couldn't help but think that It would be nice to parade around in a set of the recently added Protectorate cloths. Could this be made possible?

/spawnitem protectoratechest
/spawnitem protectoratepants

**Comment by Fevix** [comment]
Nothing is preventing you from wearing these. They just might not fit well :p
Yes it is possible, and there are plans to do exactly that.

Sent from Yahoo Mail on Android 
 
  On Wed, Jul 27, 2016 at 4:02 AM, Dragon-Tom005<notifications@github.com> wrote:   
After making my escape from the Human planet Earth, I couldn't help but think that It would be nice to parade around in a set of the recently added Protectorate cloths. Could this be made possible?

/spawnitem protectoratechest
/spawnitem protectoratepants

**Comment by Dragon-Tom005** [comment]
Maybe while your at it, how about a vanity of the Apex Frontliner armor, too?

/spawnitem apextier6shead
/spawnitem apextier6schest
/spawnitem apextier6spants

**Comment by Fevix** [comment]
Clothing modifications will take place after we have the mod in as un-buggy a place as we feel we can get it.
