### ISSUE TITLE
(On hold) Invisible blocks on some objects

### ISSUE THREAD

**Issue by Ksisa** [Fevix/Avali#209]
Theese are a few normal and minor issues, that aren't that important, but are issues nontheless
~~1. (mediocre) Firelance
![firelance](https://cloud.githubusercontent.com/assets/20682532/17176242/65600652-5414-11e6-8e3e-29460b0d6cb8.jpg)
The mechanics of how it works is ok, they do damage and shoot where i point them at, but the visuals are all wrong.
(P.S. For a super advanced civilization that is approaching singularity, their firearms are incredibly weak)~~

~~2 (mediocre) After the Jun 27th update, I can't find the Avali Display Apparatus anywhere, but I can spawn it with admin commands.~~

~~3 (minor) None of the avali consoles or light sources have wiring, even though I can press on them or turn them on/off,~~ Duplicate of #157 

4 (very minor) Some items seem to have invisible... blocks. like the Pilum display in the picture below
![blocks](https://cloud.githubusercontent.com/assets/20682532/17176234/5b5be3a6-5414-11e6-921b-5f3dd2137d6f.jpg)
It seems to be 3 blocks wide, even though it looks like 2, there are invisible blocks to the right, there are more displays that have theese invisible blocks:
All the Pilum and Hammer displays have this weird issue.
HH3, HH4, HHA1, HHA2, claw displays (without the backgrounds). the HH4 seems to not have a top-left block, and the other displays somehow "gain" blocks when I turn them to the left

~~5 (not even sure if it's a bug) The avali flag seems to be a REALLY cheap teleporter beacon~~

**Comment by Fevix** [comment]
1 is known
2 should be in one of the tabs in the nanolathe, if it isn't please tell me.
3 is known
4 Thank you for this report
5 is intended (All flags do this, IIRC)

**Comment by Ksisa** [comment]
Nope, can't find the Avali display apparatus in any of the crafting tables.

**Comment by Fevix** [comment]
It's been added in the dev version, which will be going live possibly tomorrow.
