### ISSUE TITLE
Starbound crashing on startup

### ISSUE THREAD

**Issue by ocarinaman7** [Fevix/Avali#21]
The Avali mod keeps crashing on startup and if it's supposed to be updated, why does it keep crashing?? I have the ODB2 character creator mod and it works fine, but the Avali mod keeps making it crash...help!!

**Comment by Fevix** [comment]
Please include your starbound.log contents, I cannot reproduce.

**Comment by Fevix** [comment]
I got a log from someone else. Issue is now resolved.
