### ISSUE TITLE
Guards explode, also possible uniform replacement?

### ISSUE THREAD

**Issue by TheStatic** [Fevix/Avali#210]
Specifically, any guards from the 'old' villages still remaining from pre-1.0. glitch, floran, avali, whatever... if it was a village that existed before 1.0 and wasn't altered in any way, the guards explode as soon as they come within sight.

It's most likely because you're using outdated hostile guard scripts, maybe, since the guards no longer become wary/hostile based on equipment, but rather whether or not you damage the buildings. So if you enter an old village with a weapon, the 'outdated' guards die instantly upon seeing an avali.

If it's not that, I have no idea.

Also, it's a huge pet peeve that if I recruit any avali crew members, they're forced into cramped protectorate uniforms that obviously don't fit them... is there a possibility of a patch in the future to make it so that avali wear their own version of the uniform instead? If not, I'll just have to wait til they enable the tailor and I can put everyone in a stalker uniform instead...

**Comment by TheStatic** [comment]
Oh hey, the tailors exist now.

**Comment by Fevix** [comment]
The NPCs all retain any scripts, gear, etc. associated with them at spawn, so this is an issue with Starbound, not the Avali mod

There are plans to do exactly this in the future.
