### ISSUE TITLE
Shotgun rounds exit off-center

### ISSUE THREAD

**Issue by Pheonix2982** [Fevix/Avali#216]
here are a couple of bugs with some of the weapons
the firelance has a huge hit box with its projectile/ also the projective itself is screwed up and the muzzle flash is way off
qrc(shotgun) point of exit of the rounds are slightly off 
hailstorm there is a random blue light far from the barrel
lancer(bow) what the point of the 2nd orange line?

**Comment by Fevix** [comment]
Firelance issue is known
QRC wasn't, thank you
Hailstorm also wasn't
Lancer is a compound bow.
![compound_bow_by_elroymedia-e1425384833748](https://cloud.githubusercontent.com/assets/1657108/17232061/155481ba-54eb-11e6-834a-6063df423a25.png)
