### ISSUE TITLE
Crafting UI hiding recipies

### ISSUE THREAD

**Issue by MillsV2** [Fevix/Avali#219]
With the Nanolathe getting a new UI, a lot of the recipes are hidden and can't be crafted. Unsure if this is user error or mod error. Can't really get a log for this one.

**Comment by Fevix** [comment]
Hidden how?

**Comment by MillsV2** [comment]
I know that the recipes are there, but they aren't under any of the tabs

**Comment by Fevix** [comment]
Which recipes?

**Comment by StephenMalcolm** [comment]
One particular item I see not being available for crafting is the glass bottle for decoration purposes. It's an inconsequential problem, I know.

**Comment by StephenMalcolm** [comment]
I understand that this thread might not be the place to post this question, but if you would allow me. May I ask if you have a listing of all item names so that they may be spawned through commands available, Fevix? Would really appreciate the guidance as to where to find it if it is public.

**Comment by StephenMalcolm** [comment]
Another recipe that I have had trouble finding is the spear rack.

**Comment by StephenMalcolm** [comment]
Apologies, all weapon display recipes appear to be hidden at this time.

**Comment by Fevix** [comment]
Weapon displays are crafted on the Display Apparatus. 

Bottle is in one of the tabs of the nanolathe (Update your game and you'll see it)

As for list of items, I don't even have such a thing myself.

**Comment by StephenMalcolm** [comment]
Thank you very much Fevix.
