### ISSUE TITLE
Avali grappling hook's glitched

### ISSUE THREAD

**Issue by MrMagicBeanstalk** [Fevix/Avali#226]
https://gyazo.com/d0227f15ed688d4f01c2203ec2357862
Also disables usage of techs and alternate abilities.

I've already checked other mods and they don't affect it.
http://pastebin.com/d3kTsWh9
Log file.

**Comment by Fevix** [comment]
Known issue, fixed in dev version

**Comment by Fevix** [comment]
Grappling hook is fixed, suspect a tech conflict between another mod and starbound for the tech issues.
