### ISSUE TITLE
Broken Avali Grappling Hook

### ISSUE THREAD

**Issue by Dragon-Tom005** [Fevix/Avali#228]
There's a few issues with the grappling hook that i've noticed after crafting it. One of them being that when equipped in the hotbar, you can't use the dash techs or delayed jump boost tech. 

Secondly, when you grapple a wall and then un-grapple, the hook stays stuck in the surface you've grappled to. causing a bit of a duplication glitch (from experience if you go far enough away and come back after un-equipping the grappling hook, they should go away). Also, while grappled to a surface, the ability to reel yourself in or out does not function and so you can basically walk as far as you want without limitations to where the grappling hook is.
![05e5bd408b9642459a22d8364fe536e9](https://cloud.githubusercontent.com/assets/20679216/17268227/6e5493d6-55ea-11e6-82c3-1d5cbc5124ec.png)

**Comment by Fevix** [comment]
Already fixed, update going live.
