### ISSUE TITLE
Avali Dungeon causing me to teleport back to my ship

### ISSUE THREAD

**Issue by chris05478** [Fevix/Avali#231]
For some reason, a "Avali Random" dungeon is causing me to teleport back to my ship, error is located towards the bottom of the log
[starboundlog.txt](https://github.com/Fevix/Avali/files/391767/starboundlog.txt)

**Comment by Vampyrium** [comment]
With the Avali mod, my dedicated server was causing players to be beamed back up to their ship when trying to beam down to planets with this mod installed. It also seems that the worlds that were being generated with Avali dungeons were being tagged as broken by the server software. My dedicated server log is attached.
[starbound_server.txt](https://github.com/Fevix/Avali/files/391772/starbound_server.txt)

**Comment by PAHNKAPIE** [comment]
I'm having this same problem. When I teleport down to the starting planet, I move too far to the left or right and I teleport back to my ship. I went into the game log and found this message "Caused by: (DungeonException) Unknown dungeon: 'avalirandom1'" What do I do?

**Comment by PAHNKAPIE** [comment]
Here's the text file 
[starbound.txt](https://github.com/Fevix/Avali/files/391773/starbound.txt)

**Comment by Fevix** [comment]
Error on my part, I mis-renamed dungeons. Fix inbound.
