### ISSUE TITLE
Still being removed from world and back onto the ship

### ISSUE THREAD

**Issue by VailTheWolf** [Fevix/Avali#235]
I have no idea what may be causing the issue, but I will provide my log files. Thank you.
[starbound.txt](https://github.com/Fevix/Avali/files/392008/starbound.txt)

**Comment by Fevix** [comment]
Should be fixed in 72a1be8130f89ae96ebc067f27e3492d74a16925

**Comment by VailTheWolf** [comment]
Did you update tge mod file on the forum download?

**Comment by VailTheWolf** [comment]
The*

**Comment by Fevix** [comment]
A silent update, yes.

**Comment by VailTheWolf** [comment]
Thank you.

**Comment by VailTheWolf** [comment]
New problem.
[starbound_server.txt](https://github.com/Fevix/Avali/files/392125/starbound_server.txt)

**Comment by Fevix** [comment]
redownload, possibly a corrupted download.

**Comment by VailTheWolf** [comment]
Will do.
