### ISSUE TITLE
Ranged weapons above tier 4 gone

### ISSUE THREAD

**Issue by Terkup** [Fevix/Avali#236]
All ranged weapons above durasteel have disappeared from the weapons workbench, and I can't find them at the replicator, with any addon attached, and the avali weapons license did not unlock them.

**Comment by Fevix** [comment]
They should be crafted at the bench. Try searching for "Firelance"

**Comment by Terkup** [comment]
![untitledfdssf](https://cloud.githubusercontent.com/assets/20543006/17273470/c982b712-56b5-11e6-9834-1e318fa7f5da.png)
Nothing above tier 4 there on any ranged weapon type. 

The bows are also completely gone, were they supposed to be moved to the agricultural table (Because they're not there), or removed for the inconsistency with the lore?
![untitledfds](https://cloud.githubusercontent.com/assets/20543006/17273471/c984b8be-56b5-11e6-8c33-ca744a9e58a9.png)

**Comment by Fevix** [comment]
Bench no longer requires blueprint. 
For good measure, neither does the display apparatus.
