### ISSUE TITLE
Problem with the gate

### ISSUE THREAD

**Issue by PAHNKAPIE** [Fevix/Avali#239]
Every time I try to open/activate the gate on the first planet the game crashes. I'm not sure if it's a problem with this mod or the game... I only have three mods active, Avali, Sergal, and Character creation mod. I don't really know much about these things, I was hoping this error log made sense to someone...
[starbound2.txt](https://github.com/Fevix/Avali/files/392132/starbound2.txt)

**Comment by Fevix** [comment]
Probably an issue with the game, we don't touch the gate.

**Comment by dyguren** [comment]
I'm having this same issue. Whenever i try to activate the gate with the core fragments, the game crashes…
