### ISSUE TITLE
Hoverbike animation error

### ISSUE THREAD

**Issue by VailTheWolf** [Fevix/Avali#241]
[starbound_server.txt](https://github.com/Fevix/Avali/files/392221/starbound_server.txt)
Found a consistent problem over multiple re-downloads. I just decided now to post about it. The hoverbike shard animation produces an error. I do not know if this is the only problem, as this is as far as I get in a server start up.

**Comment by Fevix** [comment]
No clue what the issue is, the only difference between our shard animation and the vanilla shard animations is the fact that one refers to a vanilla file and the other refers to our file. 

No other differences exist, even in the .png file it points to. (Aside from color obviously)

Is this problem causing a crash?

**Comment by VailTheWolf** [comment]
Yes, it is causing a crash.

**Comment by Fevix** [comment]
Can you do me a favor and verify that there is a file labeled "avalihoverbikeshard.animation" and another "avalihoverbikeshard.png" in the folder "/avali-master/animations/shards"?

**Comment by VailTheWolf** [comment]
Yes, those are the only two files in shards.

**Comment by Fevix** [comment]
Well those are the files the server is unable to find. I have no clue how to address this issue nor can I offer any advice. Your game just wants to not work :/

**Comment by VailTheWolf** [comment]
Darn. Well, thank you for at least working with me.

**Comment by UlithiumDragon** [comment]
Strange... I've been using the Avali Hoverbike for hours without any issues. It's been beaten up, hurled off cliffs, taken dips into avid, and repaired with no noticeable issues lmao.
I never let it totally break, though.

**Comment by VailTheWolf** [comment]
The server attempting to just load the animation file is causing the crash.

**Comment by VailTheWolf** [comment]
Update: /objects/glitch/trough/trough.object seems to have an error with /animations/shards/avalihoverbikeshard.animation. I might be reading logs wrong, but that's my best guess.

**Comment by Fevix** [comment]
That's a vanilla object, and wouldn't be referencing a modified thing.

**Comment by VailTheWolf** [comment]
What can I do to disable or delete the hoverbike from being accessed?

**Comment by VailTheWolf** [comment]
There's a temporary fix. Server is running fine now. Now to test client side.

**Comment by Fevix** [comment]
The issue with this fix is that as soon as someone tries to use a hoverbike, it's going to crash

**Comment by VailTheWolf** [comment]
Noted. I will warn my players.

**Comment by Fevix** [comment]
Please only close issues that are fixed.

**Comment by VailTheWolf** [comment]
I discovered the problem. WinRAR is currently corrupting certain files for absolutely reason. I extracted with windows's file browser and everything was fine and dandy. 
I would recommend putting out a warning.
