### ISSUE TITLE
No actual recipes in the avail weapon display apparatus 

### ISSUE THREAD

**Issue by ominousbrainworm** [Fevix/Avali#245]
When you open the crafting menu for the weapon display apparatus there is no recipes there. However entering Admin mode will allow you to craft them all. I don't know if this was intended and they had to be unlocked somehow but currently nothing shows.

**Comment by UlithiumDragon** [comment]
I can confirm this is a new issue, as can a few other people.

Other recipes have disappeared as well, such as all the gun past T4.

**Comment by Fevix** [comment]
And I have no idea why, the weapon and display stations BOTH are set to not require blueprints.

**Comment by ominousbrainworm** [comment]
They seem to be working properly now. I don't know if you fixed it or something has changed. But they are now showing correctly.
