### ISSUE TITLE
multiple issues as of 7-31-16 (NPC and crafting tables)

### ISSUE THREAD

**Issue by kithsakhai** [Fevix/Avali#248]
logged in today noticed several issues regarding both NPC's and crafting table recipes:

walking into a cell containing an avali NPC (on an avali character) npcs are 'despawning' showing the death particle animation and dropping pixels.  

all guards and non-quest/vendor NPC's have disappeared this morning upon logging in.

ranged weapon recipes above AM4 (durasteel level) have disappeared from weapon workbench.

all recipes from weapon rack crafting table have disappeared.

I'll update as i find new issues.

**Comment by UlithiumDragon** [comment]
Are you sure you grabbed the most recent update? The random deaths thing was fixed just recently -- some bug with the "fear on weapon out" iirc.

-----------------
Also, recipes above Durasteel haven't been at the Avali workbenches for some time now. You need to check the relevant vanilla end-game crafting tables for them (i.e. Separator Table, Manipulator Table, etc.).

Also, you will get the recipes for the final armor sets (the ones made with Solarium Stars) once you craft the lower level ones used as a material for said sets.
For example, you won't have the recipe for the Ferozium Helmet Insert until you've crafted the Aegisalt Helmet Insert.

Now, if you were talking about the guns, those display perfectly fine for me still...
-----------------
All weapon rack recipes were moved to the new "Avali Display Apparatus" crafting station. Iirc, it's crafted at the Nanolathe.

**Comment by Fevix** [comment]
It's a lot easier on us if you post a separate thread per issue, as we can close the issues that have been resolved.

Please post your starbound.log so we can work on isolating a few of these issues.

**Comment by kithsakhai** [comment]
GitHub wont accept a TXT or ZIP like it says, not sure why...
