### ISSUE TITLE
Tier 5+6 Melee Weapons

### ISSUE THREAD

**Issue by IceColdas** [Fevix/Avali#249]
After building the Replicator upgrades, the Avali Tier 5 and 6 melee weapons show up in the crafting table. The crafting recipes for these weapons seem to still use the old versions (Rubium > Perfectly Generic Item).

Either these recipes should be disabled (No other race normally has T5/6 weapons from these crafting stations AFAIK), or the crafting recipes (and names?) should be looked at again.

**Comment by UlithiumDragon** [comment]
I do see some weapons still with outdated recipes, such as:

- SK7 Glacier (Manipulator's Table)
- HHM2 Frost (Manipulator's Table)
- VL7 Icicle (Manipulator's Table)
- VABA2 Shard (Accelerator's Table)

However, I only see one or two T5/T6's, and all I see have working recipes.
Which table are you looking at, specifically...?

**Comment by IceColdas** [comment]
I had checked all tables. From the Separator table: The VBS1 Shard (1h Sword-T5) requires a Solarium Star x12 and Perfecty Generic Item x12. 

For the Manipulator table: The HHM2 Frost (Dagger-T6) requires 8x Perfectly Generic Item.

I noticed that the Ferozium items are still coloured red from Rubium (But that's just small details).

To clarify on the "renaming" mention; Some items follow a pattern, others don't. Daggers from the Manipulator table are listed as "HHM1" for example. The Manipulator versions of the Hammer don't however; SK7 Glacier = T6 and SK9 Glacier = T5. Again, just minor details.

**Comment by Fevix** [comment]
SK7 and the like are holdovers from the days when there was a single direct line from copper to impervium, and impervium was the topmost tier. Internally, the items are still called the same (IE, avalitier7broadsword), however, this is likely to change in an upcoming patch. 

As for the coloring stuff, that's a similar issue, we have each item coloring to its tier (Like the broadsword above, coloring to tier 7), and have not yet invested the time to modify the weapons, focusing more on game-breaking bugs. 

We're coming out on this bugfix-only mode soon, however, and one of the team members has already begun work on changing the weapons.
