### ISSUE TITLE
Avali Dungeons failing

### ISSUE THREAD

**Issue by HMikz** [Fevix/Avali#251]
I was beaming down to a new Forest planet that was moderate and all of a sudden I get beamed back up to the ship. Seemingly that is odd, so I look at the Server Console and the log shows me that an issue has occurred with spawning Avalirandom1 dungeon.
It has also affected another forest planet in the solar system, this time Avalicamp failed to load. I am not sure if FrackinUniverse (as is installed too) may have conflicted with the dungeon spawning.
Note restarting the server did nothing, and keeps happening on these Forest Moderate planets.

Edit: I cannot progress the quest to get clues for the Hyotles in the Temperate Solar Systems.

[starbound.txt](https://github.com/Fevix/Avali/files/394829/starbound.txt)
[starbound_server.txt](https://github.com/Fevix/Avali/files/394831/starbound_server.txt)

![image](https://cloud.githubusercontent.com/assets/20765069/17284173/33f7af96-576d-11e6-9167-37c0f4feb115.png)
![image](https://cloud.githubusercontent.com/assets/20765069/17284222/b4961232-576d-11e6-9586-870251404bee.png)

**Comment by Fevix** [comment]
So this issue is fixed?
