### ISSUE TITLE
Players not able to teleport down planetside

### ISSUE THREAD

**Issue by ColorshyTheDull** [Fevix/Avali#253]
These are some logs posted in the Steam Workshop comment section by " அεలεໄ ". The user reported being able to teleport down after removing the Avali mod.
[Starbound.txt](https://github.com/Fevix/Avali/files/394461/Starbound.txt)
[Starbound (2).txt](https://github.com/Fevix/Avali/files/394462/Starbound.2.txt)
[Starbound (3).txt](https://github.com/Fevix/Avali/files/394460/Starbound.3.txt)
[Starbound (4).txt](https://github.com/Fevix/Avali/files/394458/Starbound.4.txt)
[Starbound (5).txt](https://github.com/Fevix/Avali/files/394459/Starbound.5.txt)

VVChronological order of two players reporting on the same problem.VV

Cheese Daddy: Hey guys, Anyone facing an issue where you would teleport back to your previous position first before successfully teleporting? I.E you beam from your ship to the outpost, but as soon as you arrive you get beamed back to the ship. on the second try you make it through without issues

அεలεໄ: Cheese Daddy ! yes, me and my friend ! Allways have to teleport twice! I

அεలεໄ: ok, I put this mod off my game and the beaming is working again very best.

அεలεໄ: I not seen Colorshy answer before Oo' sorry.

<URL Removed>

Here are the 5 starbound log.

I let now the mod off, because I can't beam to the Floran mission. I don't want pb with can't beaming and must off the mod and have lost the mod items.

I'd made a vid and when beam to planet or outpost or the mining mission then can see short arrived there but instant beam back. In Floran Mission is no arrive, its beam to ship teleporter and beam instant back to the bord computer. Never arrive Floran Mission.
If you like to see this video I can upload it on you tube.

I will be happy when you fix this issue and I have Avali back in game :) thank you !

**Comment by Fevix** [comment]
[17:04:03.620] [Warn] Unable to set requested display resolution 1920, 1080

There's one issue, but this isn't affecting the beaming. Unfortunately, I have experienced this issue (Even occasionally getting beamed back off my ship of all things) but it never puts anything in the log.

**Comment by UlithiumDragon** [comment]
"...after removing the Avali mod."

You simply CANNOT remove mods that make changes to the universe. I'm not 100% sure if this applies to dungeon generation, but I'm pretty sure that it does.
I do know it applies to anything that alters terrain gen or adds new kinds of planets (i.e. the mod Frackin' Universe).
