### ISSUE TITLE
(Fixed - 1.0.2) Avali villager guards are walking around with matter manipulators.

### ISSUE THREAD

**Issue by IxeyDergon** [Fevix/Avali#260]
After the update that changed the weapon names, Avali guards in villages now carry around matter manipulators holding Perfectly Generic Items.

[starbound.log.txt](https://github.com/Fevix/Avali/files/403097/starbound.log.txt)

![screenshot_1](https://cloud.githubusercontent.com/assets/20842958/17425253/299a8d32-5a99-11e6-8673-8730116cfe29.jpg)

**Comment by jaydee0004** [comment]
I can attest to this. Same issue mine. Using the latest version too.

**Comment by jaydee0004** [comment]
Causes crashes too.

**Comment by Jeadbe** [comment]
Are these guards in villages that you explored/found before the update? If so, this is likely because the items they're wielding no longer exist.

**Comment by Fevix** [comment]
Like Jeadbe said, it's entirely likely that the item they're trying to weild no longer exists (NPCs like to save too much information in their files)

**Comment by IxeyDergon** [comment]
I was aware that it was caused by the weapon rename change to the mod. I erased the world file for the planet they were on to start the planet anew, it fixed all the weapon issues except for one guard who did not get the memo. He still has the perfectly generic item.

**Comment by Fevix** [comment]
That's probably something I missed, can you post the starbound.log of when you regenerated the planet?

**Comment by IxeyDergon** [comment]
[starbound.log(2).txt](https://github.com/Fevix/Avali/files/404872/starbound.log.2.txt)

According to this log, which was when the avalicamp was generated, there is an item exception for the minigun?

**Comment by Fevix** [comment]
This issue here is with a typo. I've since caught this typo and fixed it. 

I'm marking this resolved, but leaving this open until the update that fixes it goes live (This Friday)
