### ISSUE TITLE
Non-avali characters unable to access roof and furniture in nanoloom

### ISSUE THREAD

**Issue by TheStatic** [Fevix/Avali#263]
Basically what the title says, I've passed off avali crafting tables to friends and other characters for those who want to build avali houses and communities without being an avali themselves... However, for some reason quite a number of the necessary building materials are inaccessible on the nanoloom for non-avali... in fact, everything except for the tiles/blocks are missing. I can understand locking away the clothing, but it causes an issue when the roofing, wall pieces, doors, and cloth furniture are all missing.

Is there a reason behind this, or a bug that's gone unnoticed?

**Comment by Fevix** [comment]
The reason behind this is that all stations EXCEPT the nanoloom require no recipes known. 
The nanoloom cannot have the same done to it, because it also uses the "loom" tag, meaning that it would be able to craft EVERYTHING you can make on a loom, without you needing to know the recipe.

**Comment by TheStatic** [comment]
Will this possibly be fixed in the future when you discover a way to, for example, affix upgrade tiers to the loom?

**Comment by Fevix** [comment]
I could just include a few select loom recipes (Such as cloth and the like) and make it once again not require recipes.
