### ISSUE TITLE
Mis-tiered equipment, tooltip for aeroponics, pixel printer?

### ISSUE THREAD

**Issue by TheStatic** [Fevix/Avali#264]
All of the avali-themed agricultural equipment, drills/pickaxes, and flashlights are durasteel upgrade only, which is very unfitting as they're all clearly intended for iron-tier. Only the grappling hook and chainsaw should be locked to durasteel, while the rest should be accessible as soon as the agricultural table is unlocked.

More of a suggestion than a bug, but could the Aeroponics Tubes have a description/tooltip about that they don't need to be watered, merely tilled? Not many new Avali mod users will pick up right away that the tubes are self-watering and do not require the watering pail. (I keep forgetting, myself...)

Also, do you have plans to make all the avali furniture and non-block building materials be Pixel Printer compatible? Not only this would make it helpful for non-avali characters to be able to recreate and collect avali stuff without having to loot the villages, but this could help with not having to stuff everything in the crafting tables in the future, and be able to restrict some things to scans and recipes.

**Comment by Fevix** [comment]
All of these are great suggestions and are likely to be implemented in the near future
