### ISSUE TITLE
(Fixed - 1.0.2) SAIL skipping wakeUp Dialog

### ISSUE THREAD

**Issue by leinglo** [Fevix/Avali#267]
The "I am S.A.I.L," "Earth was attacked" dialog that should occur after rebooting is being skipped for some reason, it just goes straight to offering the Getting Started quest.

**Comment by Fevix** [comment]
Fixed in dev version. Issue remaining open until hotfix goes live.

**Comment by Fevix** [comment]
Issues that are fixed but the fix hasn't been released remain open
