### ISSUE TITLE
latest hotfix crashes the game at start

### ISSUE THREAD

**Issue by ryl-hannibal** [Fevix/Avali#268]
game crashes after launch because of recent fix "First batch of hotfixes!"

**Comment by Fevix** [comment]
Cannot fix due to: 
Unable to replicate on own installs
Lack of starbound.log preventing true blame-pointing

**Comment by ryl-hannibal** [comment]
which one i have 1 starbound.log and 5 with (1-5) numbers

**Comment by Fevix** [comment]
Just the .log

**Comment by ryl-hannibal** [comment]
...........something weird just happened it played.. huh.. sorry for the inconvenience
