### ISSUE TITLE
crashes the game at start when i install avali mod

### ISSUE THREAD

**Issue by AzizArouss** [Fevix/Avali#269]
the game stops working when I want to install the mod manually (...\Steam\steamapps\common\Starbound\mods) the problem is that when I install another mod for a new race, everything works fine but when I want to install this one, nothing works.

the log : http://pastebin.com/j9e17M66

**Comment by Fevix** [comment]
`[18:22:47.190] Info: Client Version 'Beta v. Glad Giraffe - Update 3' Revision: 30555b17a491c2a97ab0afbff3b848a1fd937dbd Protocol: 711`

This is what my (up to date) client version looks like: 
`[04:47:21.647] [Info] Client Version 1.0.5 (windows x86_64) Source ID: 7d4a2bbba04d43bd7f43f0ca940db23b2187edc1 Protocol: 724`

This mod will only work in updated versions of the game.
