### ISSUE TITLE
 crash game even after update

### ISSUE THREAD

**Issue by AzizArouss** [Fevix/Avali#271]
I just update the game to have it in 1.0.5, but the game still does not work when I want to install the mod manually, sorry for the inconvenience again.

log : http://pastebin.com/DLGhpt6x

**Comment by Fevix** [comment]
[06:25:14.381] [Info] Loading assets from: '..\mods\Avali-2.5.0'

You're using an outdated version of the mod. Please update with this link: 
https://github.com/Fevix/Avali/archive/Triage.zip

**Comment by AzizArouss** [comment]
Same problem here, with the new version of the mod.

[06:38:30.585] [Info] Loading assets from: '..\mods\Avali-Triage'
log : http://pastebin.com/KdRS4zg2

**Comment by Fevix** [comment]
Old issue, no known fix. 
Game is failing to find a file that's exactly where it's looking for it at.

**Comment by AzizArouss** [comment]
So there is no resolution to the problem ? Because I has actually install it on a server, but if locally it does not work, it does not work on the server we agree ?
