### ISSUE TITLE
Can't approach custom-built Avali hub, forced beam to ship. Avali items also missing.

### ISSUE THREAD

**Issue by Jaycemonde** [Fevix/Avali#275]
I started my Avali character up and tried to teleport down to a large hub I created on a planet via **Avali nanotech teleport**, but as soon as I did so I was instantly booted off-world, same result if I try to approach it on-foot. The teleport disappeared from my transport list afterward.

My **Firelance** is missing, too, as are a few things like the **Nanoloom** and **Nanolathe**, all replaced with **generic objects**.

_Avali NPCs_ and most of the **Avali tent objects** seem fine, as does the shipworld itself and any decorations I had placed on it (with the exception of aforementioned crafting stations). I have two _Avali crewmembers_ aboard my ship and I have no issues with them.

I thought it might be an issue with the warpgate on the planet (as I built the hub right next door to it), but I don't see how that could be the case. I also had a suspicion it may be related to _Avali NPCs_ I created accidentally while fumbling around with the _Create-a-Friend mod_, since I have one each in both the large Hub and a smaller settlement I created nearby, though as I got rid of the **Create-a-Friend spawners** and only the _bugged NPCs themselves_ remain I can't imagine how that would be the problem, especially as several bits of Avali tech are being turned into **generic objects**.

Starbound.log files included below.

[log files.zip](https://github.com/Fevix/Avali/files/405965/log.files.zip)

**Comment by Fevix** [comment]
I'm going to need a log of you approaching this hub and getting beamed up. Follow these instructions to get the best possible log that can let me pin down your problem: 

1. Restart the game completely. Close out of it and relaunch.
2. Load up the character that's in position to get to this hub
3. Approach the hub
4. When you get beamed back up to your ship, save and quit the game, then exit completely. 
5. In the same folder you found the above files in, look for either "starbound.log" ot "starbound.txt". Open this file in a text editor such as Notepad, then copy everything and paste it as a new paste at http://www.pastebin.com
6. Send me the URL of the page after you click "Create New Paste"

**Comment by Jaycemonde** [comment]
http://pastebin.com/CQeQH1w6

This time, when I got to the sector that would normally have the small in-between camp leading to the Hub, the game just failed to generate the entire thing and I was left with a hard end to the world. Walking into it triggered the beam-up.

**Comment by Fevix** [comment]
Unfortunately, the only errors pertaining to the avali mod I'm seeing are the bits about the weapons we removed (We removed the tiered guns in favor of a more compact system to do the same thing)

The one causing the crash is something I've never seen before: 
```
[22:11:47.740] [Error] WorldServerThread exception caught: (WorldStorageException) WorldStorage generation failed while generating from queue
Caused by: (ToolUserItemException) Not initialized in ToolUserItem::entityMode
```

**Comment by Jaycemonde** [comment]
That's really weird. No chance that it's connected to Frackin' Universe or another mod along those lines?

If it's not out of the way to ask, what kind of changes are being made to weapons? Will that affect what NPCs are carrying around?

**Comment by Jaycemonde** [comment]
Well, I'm about 80% sure the problem lies with Frackin' Races or Frackin' Universe, which both received a glut of updates recently, but I haven't gotten a response back from the dev as yet. Nothing on my end has helped, either. The problem seems to persist with all other Avali settlements I approach, and other people are saying they've got problems with Avian areas too, so I think it might be related to some kind of parasol-type code he implemented to make Avali and Avians fall more slowly. I don't know.

Anyway, thank you for the quick response and help.

**Comment by Fevix** [comment]
If you hear back from Sayter, please do come back and close this issue.

**Comment by Jaycemonde** [comment]
Sorry for the delay. I heard back from him, but all he could tell me was that it was an issue with either the shipworld or world with the issue having duplicate sectors.
