### ISSUE TITLE
Incorrect spear secondary attack?

### ISSUE THREAD

**Issue by TheStatic** [Fevix/Avali#282]
I decided to switch to using spears, but I noticed that the avali spears have Parry as their secondary attack. Which is not only practically useless, but it's a broadsword secondary, not a spear secondary.

I'd recommend the Barrier special, but I'm not sure how that would work without an elemental alignment (though Frost/ice would not only be very fitting for avali, but also pairs well with Barrier as a defensive combo).

On the other hand, you could also devise or try to find a 'bleed' status condition to go with the lore of aerogel shards breaking off inside the enemy.

Either way, can it please not be Parry of all skills?

**Comment by Fevix** [comment]
Craft one from a different station (Separator, Accelerator, and Manipulator all have different alternate abilities)

**Comment by TheStatic** [comment]
Still, Parry is an almost entirely useless secondary that makes the spear (since it has parry all the way until the final tier) very unappealing and wouldn't really come into use even for spearwielder players til they discover that the different tables give different secondaries.

Kind of a shame for a species that largely favors spears.
