### ISSUE TITLE
Tech image issue

### ISSUE THREAD

**Issue by RiyuG** [Fevix/Avali#285]
Don't know if anyone else has noticed this. Went to the outpost to get some tech when I noticed the icon of the person was a humanoid male. Guess that the old custom Avali images for equipping tech haven't been implemented, but the interesting point is that I'm an Avali Female, so figure might as well point that tidbit out for the bug hunters.

**Comment by Fevix** [comment]
known, but with Ryuujin taking over, won't be fixing. Ryuujin will more than likely make his own version in his update.
