### ISSUE TITLE
Bad recipes for avali miner set

### ISSUE THREAD

**Issue by gamrguy** [Fevix/Avali#291]
The avali miner set has recipes which are still using the old "spinningwheel" category as opposed to the new category(ies).

From recipes/crafting/clothingstation/avaliminerchest.recipe:
(and avaliminerhead.recipe)
`"groups" : [ "spinningwheel" ]`

This makes the set impossible to obtain during the course of regular play without the use of admin mode.

**Comment by Harakhti** [comment]
It was made to be assigned to its own station, which wasn't implemented at the time. It wasn't meant to be obtained.

**Comment by Harakhti** [comment]
Solved by https://github.com/Fevix/Avali/pull/295
