### ISSUE TITLE
Missing ship computer

### ISSUE THREAD

**Issue by KomissarbAv** [Fevix/Avali#292]
My ship computer disappeared while I was moving some furniture around in the main compartment/ first room on the ship. Everything else seems to be working in proper order.

I'm currently at the T4 ship upgrade at 8 crew members, two being Avali.

I have no idea which is the actual starbound log, since they were all written at the same time, but I'm guessing it may be Log 2 or Log 4, judging by the size.

[starbound logs.zip](https://github.com/Fevix/Avali/files/416761/starbound.logs.zip)

**Comment by KomissarbAv** [comment]
Also, writing here because I set up a discussion on Steam last night about the issue but it got closed quickly because the moderator said it was a mod issue.

**Comment by KomissarbAv** [comment]
I just found a guide from 2014 but wasn't sure about the game version, turns out I had to delete the shipworld file and everything resets, while keeping crew and ship size.

Either way, it would probably be a good idea to look into this.

**Comment by atwas** [comment]
Have the same issue that just appeared. Ive done the first mission (erchiuus) and when i booted up, SAIL is gone from my ship. Deleting the shipworld files did NOT fix it for me. 
[storage.zip](https://github.com/Fevix/Avali/files/416850/storage.zip)

**Comment by Fevix** [comment]
/admin
/spawnitem avalitechstation
/admin

Problem solved, I left these instructions on both the forums and the workshop.

**Comment by KomissarbAv** [comment]
Cool, thanks for the tip.
