### ISSUE TITLE
Avali crew clothing bug

### ISSUE THREAD

**Issue by Dimasw99** [Fevix/Avali#297]
My Avali crew members are wearing vanilla clothes instand of the avali clothes.
![20160818100759_1](https://cloud.githubusercontent.com/assets/21098781/17766725/cb472774-652c-11e6-9bbf-0d7ed8314629.jpg)

**Comment by Fevix** [comment]
There are no avali clothes for the crewmembers furrently.

**Comment by Dimasw99** [comment]
i think it would not be that hard to fix just check for race and change clothes i might even take a look to fix it
