### ISSUE TITLE
Anchor point for the "Fold-up Table" is in the wrong spot.

### ISSUE THREAD

**Issue by UlithiumDragon** [Fevix/Avali#299]
The placement anchor point for the "Fold-up Table" is not correct. It is actually one grid block down from the actual object, as well as anchored on the far left of the object.

This means it cannot be placed efficiently, and will block other objects from being placed in areas that it does not actually occupy.

Example:

![20160818181702_1](https://cloud.githubusercontent.com/assets/6376917/17792720/796974ea-6570-11e6-847b-92801728925d.jpg)

![20160818181659_1](https://cloud.githubusercontent.com/assets/6376917/17792710/6d39a5fa-6570-11e6-95c5-b1da039eacec.jpg)

![20160818181710_1](https://cloud.githubusercontent.com/assets/6376917/17792724/8186fe72-6570-11e6-83f8-512ee7c5f3f7.jpg)

![20160818182152_1](https://cloud.githubusercontent.com/assets/6376917/17792801/f55b247c-6570-11e6-856c-835d8af4d45c.jpg)

**Comment by Fevix** [comment]
Fixing anchor point would cause all tables to move and potentially cause crashes. As this is purely QOL, a fix will not be released.

**Comment by UlithiumDragon** [comment]
Wait wait wait wait - no, WTF are you talking about??? This is a VERY common error that has existed since Starbound has!!!
And why the hell would it cause CTD's???

PARTICULARLY on this object, where the placement anchor point is actually OUTSIDE of the object's bounds ffs!!!

I'm gonna go fix it myself on my end if you won't, as these are very obnoxious placement bugs that do nothing but inhibit building with the objects in question...
