### ISSUE TITLE
Anchor point for the "Avali Table" is in the wrong spot.

### ISSUE THREAD

**Issue by UlithiumDragon** [Fevix/Avali#300]
The placement anchor point for the "Avali Table" is not correct. It is anchored to the far left side of the object rather than the middle.

This leads to placement inconsistency issues and causes the object to take up space that it does not actually occupy, but ONLY on the left side.

Example:

![20160818182634_1](https://cloud.githubusercontent.com/assets/6376917/17793007/5b986faa-6572-11e6-9f77-cda01359ebbe.jpg)

![20160818182649_1](https://cloud.githubusercontent.com/assets/6376917/17793011/61170bee-6572-11e6-9268-db69ceda4115.jpg)

![20160818182655_1](https://cloud.githubusercontent.com/assets/6376917/17793013/64052a7a-6572-11e6-8a0a-0a981c7638f5.jpg)

**Comment by Fevix** [comment]
Fixing anchor point would cause all tables to move and potentially cause crashes. As this is purely QOL, a fix will not be released.

**Comment by UlithiumDragon** [comment]
Wait wait wait wait - no, WTF are you talking about??? This is a VERY common error that has existed since Starbound has!!!
And why the hell would it cause CTD's???

I'm gonna go fix it myself on my end if you won't, as these are very obnoxious placement bugs that do nothing but inhibit building with the objects in question...

**Comment by Fevix** [comment]
I'm talking about placed tables here. if you change the anchor point, the table moves (I had someone test this and yes, they do move)
Anything on the table when it moves, or anything that's where the table is trying to move, could cause a CTD (Either when the object that's supposed to be anchored at the bottom suddenly isn't anchored to anything, or when two objects attempt to occupy the same place, or when an object and a foreground tile try to occupy the same place.)

**Comment by Fevix** [comment]
Additionally, regarding your comment on the forums, no, we have NOT changed the anchor points for ANY of the objects.
