### ISSUE TITLE
Crash on Tenant Spawn or Spawn/Despawn Merchant Loop

### ISSUE THREAD

**Issue by Urrurrual** [Fevix/Avali#301]
I am working on making an Avali village, had managed to get a regular villager and a guard, and was working on getting a merchant. My first run around I didn't have enough commerce blocks, so I corrected the issue and removed and replaced the deed and a new villager (presumably a merchant) spawned. He started to do his own thing, I hit E on him, and my game hung and crashed. I have a fairly extensively modded game (All the mods I use: [http://steamcommunity.com/sharedfiles/filedetails/?id=731614556](url) ) , so I thought nothing of it at first, Restarted, spawned my character and noticed I had been rolled back to the last teleporter use before the crash, and my inventory adjusted to before I'd placed the final commerce blocks. Attempted to finish it again, and crashed again, this time after the villager spawned before I clicked on it. I have pastebinned the file you asked for from the second crash. [http://pastebin.com/nyDkMnw4](url)

**Comment by Fevix** [comment]
You don't have to insert urls manually if you're posting links. Github will do it automatically.

Investigating...

**Comment by Fevix** [comment]
This doesn't look like your full log. I don't see any information about a crash. The tenant errors you're seeing there are being caused by the Viera mod, but I can't give you anything more than that.

**Comment by Urrurrual** [comment]
They were Avali Tenants, so it's weird I'm getting errors from Viera.. Oh hey, this site also lets me upload files.  also had logs saved as .1 files and other such nonsense which is weird. I'll upload each of the files now and my config file.

[starbound.log.txt](https://github.com/Fevix/Avali/files/427095/starbound.log.txt)

[starbound.log.1.txt](https://github.com/Fevix/Avali/files/427087/starbound.log.1.txt)

[starbound.log.2.txt](https://github.com/Fevix/Avali/files/427088/starbound.log.2.txt)

[starbound.log.3.txt](https://github.com/Fevix/Avali/files/427085/starbound.log.3.txt)

[starbound.log.4.txt](https://github.com/Fevix/Avali/files/427084/starbound.log.4.txt)

[starbound.log.5.txt](https://github.com/Fevix/Avali/files/427086/starbound.log.5.txt)

[starbound.config.txt](https://github.com/Fevix/Avali/files/427091/starbound.config.txt)

**Comment by Urrurrual** [comment]
Third Time's the charm. New info. Got it to not crash when placing the colony deed,and now the tenants are de-spawning a couple seconds after spawning.

http://steamcommunity.com/profiles/76561198004480268/screenshot/273978479656483120

[starbound.log.5.txt](https://github.com/Fevix/Avali/files/427224/starbound.log.5.txt)
[starbound.log.txt](https://github.com/Fevix/Avali/files/427221/starbound.log.txt)
[starbound.log.1.txt](https://github.com/Fevix/Avali/files/427220/starbound.log.1.txt)
[starbound.log.2.txt](https://github.com/Fevix/Avali/files/427222/starbound.log.2.txt)
[starbound.log.3.txt](https://github.com/Fevix/Avali/files/427225/starbound.log.3.txt)
[starbound.log.4.txt](https://github.com/Fevix/Avali/files/427223/starbound.log.4.txt)

**Comment by Fevix** [comment]
Issue does not stem from Avali. Recommend backing up universe and player folders then removing race mods one by one until the issue vanishes.
