### ISSUE TITLE
My friend has a glitched ship!

### ISSUE THREAD

**Issue by ocarinaman7** [Fevix/Avali#34]
hi, my friend has a tier three ship with the avali, and he has the research station, something that should ONLY appear at tier 5, I have a tier 4 ship and I don't have the station yet...here are some pics, first is a pic of his, second is one of mine
![early research station](https://cloud.githubusercontent.com/assets/13989420/9669703/9e56b69c-523d-11e5-941a-9873f048af27.jpg)
![my ship](https://cloud.githubusercontent.com/assets/13989420/9669736/cb4d5d36-523d-11e5-87f8-995574e4b5fe.jpg)

**Comment by Fevix** [comment]
I believe the research station was removed in the recent versions. You and your friend should upgrade ship.

**Comment by ocarinaman7** [comment]
that's weird cause it suddenly appeared on his ship yesterday, with the most recent update. I just upgraded my ship to tier 5 and still nothing

**Comment by Fevix** [comment]
Are both of you using the most recent version of the mod?

**Comment by ocarinaman7** [comment]
yes, before it was just updated, I just upgraded my ship to the full version and still no station

**Comment by Devani1** [comment]
The research station is still in the most recent version. Neither of those ships are tier 3, the lowest one is tier 5 (top picture). Was your ship made before the edited Avali research station was in the game? If so, that could be the reason why you don't have one.

**Comment by ocarinaman7** [comment]
my ship is the top tier with the most recent update, and it still isn't there

**Comment by ocarinaman7** [comment]
well, now it is anyway

**Comment by ocarinaman7** [comment]
and Devani? no, that ship isn't tier 5, I wen to his ship, mine was larger at that point

**Comment by Devani1** [comment]
/admin then /spawnitem shipT5. Use this on a new character to see what I mean.

**Comment by Devani1** [comment]
The vanilla races also get the research station at this tier as well.

**Comment by thakyZ** [comment]
I have always gotten mine at tier 3 even on all races

**Comment by Devani1** [comment]
Closing the issue in two days, or less.
