### ISSUE TITLE
Tier0 object files not loading

### ISSUE THREAD

**Issue by TheSpiderDungeon** [Fevix/Avali#35]
Whenever I try and load the game with this mod, it says that the t0 ship objects can't be loaded. I removed them and it loaded fine, but the game crashes when trying to play a new character.

**Comment by TheSpiderDungeon** [comment]
I should also add I'm running 1.6.9 of the mod on Spirited Giraffe if that's the incorrect version.

**Comment by Fevix** [comment]
Starbound.log please.

**Comment by Devani1** [comment]
T0 ship objects should have been fixed awhile ago. Try deleting your Avali folder and re-downloading it.
Thanks, if it crashes again we will need the starbound.log.

**Comment by Fevix** [comment]
Devani to the rescue
