### ISSUE TITLE
Merchant Prices

### ISSUE THREAD

**Issue by SpaceEngineerRaptor** [Fevix/Avali#42]
The prices of some items in the merchant are 0, and that causes the game to not let you buy them, i have made a small patch for me and my friend fixing a lot of them, but i was afraid to attempt the guns, melee, and armor, due to balancing.

**Comment by Fevix** [comment]
Known issue. Prices for items have moved to the actual item. I'm not sure how recipe pricing works.

**Comment by SpaceEngineerRaptor** [comment]
i disected gardenbot's price of 750 and jsut moved it over to the avali items one by one, it took about 30 minutes to get a good chunk of items, and i noticed the avali merchants from the tennants system mostly sell instruments, is that a bug aswell?

**Comment by Fevix** [comment]
I have not personally looked into the tenant system. You'd have to ask the one who worked on them, @Luthor614

**Comment by Luthor614** [comment]
Hey Fevix, I'll see about working on some prices on my end dude.

**Comment by Luthor614** [comment]
Just delving into the Vanilla price structure so will need some time to tweak em'. The merge you just did still doesn't 100% fix the selling structure so will see what I can do :)

**Comment by Fevix** [comment]
Any progress?

**Comment by Luthor614** [comment]
This should've been fixed with one of those last pushes dude...haven't had
a chance to play yet as am working now. However, i literally just modelled
it after vanilla so in theory everything should be jammy. If not well we'll
take er' back to the old drawing board :)

**Comment by Fevix** [comment]
I'll go ahead and close this then.
