### ISSUE TITLE
Avali strip light pointing right instead of down

### ISSUE THREAD

**Issue by Fevix** [Fevix/Avali#52]
https://github.com/Fevix/Avali/blob/master/objects/avaligeneric/lights/avalistriplight.object#L20

I suspect this line (Highlighted) has something to do with it

@thakyZ @Devani1 @Mackinz

**Comment by Devani1** [comment]
can't do this right now but try putting light angle to 180 instead of 90.

**Comment by Harakhti** [comment]
pointAngle needs to be beamAngle. Values should be unchanged.

**Comment by Fevix** [comment]
Fixed in #55
