### ISSUE TITLE
Armor Q&A w/ regards to Vanilla Progression

### ISSUE THREAD

**Issue by Luthor614** [Fevix/Avali#53]
So I'm gonna throw this out here...we've got Avali tier progression kinda setup in the old sense currently, i.e. tier 1-10 as opposed to tier 1-4, then branching off to the different tables the way CF does it. 

Question really is: keep it as is? -OR- streamline it to something more Vanilla like?

**Comment by Luthor614** [comment]
This will also kinda determine how I go about adjusting the guard npc's & tenants accordingly :)

**Comment by Luthor614** [comment]
OTHERWISE I can always just make some defaulted "guard" armor to be more in line with Vanilla, then that may solve my armor insert issue (since npc's can't use vanity slots)...

**Comment by Fevix** [comment]
Vanilla doesn't really have branches, just 3 versions each of tiers 5 and 6. 
The "avalitier10_____" stuff is a holdover from before, when it /did/ go to 10.
If we change "avalitier10_____" to "avali-tier6accelerator", then all of the gear will suddenly PGI and force players to remake it all.
As it is, this is entirely a backend thing. Players aren't affected, for the most part, unless they're trying to spawn items in. In which case they're hopefully smart enough to peek into the files to see what the name of the item they're trying to spawn in is.

**Comment by Luthor614** [comment]
So I'll go with making custom guard armor then dude, already started on it...and will leave the tiered armor be.

**Comment by Luthor614** [comment]
And I can probably close this "issue" :) just didn't really know where to message you easily.
