### ISSUE TITLE
Unbalanced weapons

### ISSUE THREAD

**Issue by Fevix** [Fevix/Avali#66]
@Devani1 @thakyZ @Luthor614 @Sparrows413 
@anyone else who feels like working on it
Please reply to this before starting work, so we don't have 2 people working on it at once.

**Comment by Devani1** [comment]
I'll start to work on them, I'll give updates after I finish a weapon teir. I'll start with broadswords. (I'll be comparing them to the human weapons, hopefully that's okay)

**Comment by Devani1** [comment]
Finished all the melee weapons, and merged them.

**Comment by Fevix** [comment]
That doesn't seem like that big of a change, though. Have you tested ingame to see if they scale properly? Last I saw, a T4 shortsword and a T6 shortsword had identical stats.

**Comment by Devani1** [comment]
I'll double check, but the only difference I could detect was the "level" value. The higher the level the more damage it does.

**Comment by Devani1** [comment]
I checked all the melee weapons in-game, and I found only 2 weapons that had a small error. Fixed.

**Comment by Devani1** [comment]
I'm a bit confused on where to start with the guns. I could use the Novakid's craft-able guns, but I'm not sure where to group in the firelance. I do know it is a bow, but should it be as powerful as a gun/sniper?

**Comment by Fevix** [comment]
The firelance should have roughly the same DPS as the snipers, yeah, factoring into account the fact that it takes a while to charge up to max damage.

**Comment by Devani1** [comment]
AvaliBow_t1 = Iron Bow,
AvaliBow_t2 = Steel Bow,
AvaliBow_t3 = Compound Bow,
AvaliBow_t4 = Frozium Bow
Any idea where I can find an easy comparable for the guns? Starbound randomly generates their guns other than the Novakids revolver and riles, so they won't work for all the guns.

**Comment by Fevix** [comment]
Other then modifying, relaunching, obtaining a fresh one and seeing how it stacks up against equal leveled random guns of the same type, no.

**Comment by Devani1** [comment]
I think guns are fine for now, what we really need to do is update the pilum damage.

**Comment by Fevix** [comment]
So that's it, no more unbalanced weapons?

**Comment by Devani1** [comment]
The guns might be off slightly,  maybe by 1 or 2 damage, but nothing huge, so yeah, I'd say so.

**Comment by Fevix** [comment]
Tier 6 guns and most melee weapons are still quite weak, even on tier 1 planets.

**Comment by Devani1** [comment]
Resolved
