### ISSUE TITLE
Ship upgrade crash/messup

### ISSUE THREAD

**Issue by Dakumi** [Fevix/Avali#82]
Occasionally when I upgrade my ship it seems to 'crash' and become unusable and randomly reassembled. Is there a specific reason for this that anyone has found?

So far I've been told it's because of objects around the ship or from playing multiplayer, but it's happened at least once or twice in single player. Currently it's very rare in the latest updates, but I've had to keep a keep-safe copy of my saves between ship upgrades.

**Comment by Fevix** [comment]
Next time this happens, send in your starbound.log and we'll see what we can find out.

**Comment by Devani1** [comment]
This is strange, I've had three or more players switch between my small private server, to single player and upgrade the ship on both and we never experienced this. I've also made many test characters and upgraded the ships more times than i wish I had.

**Comment by Dakumi** [comment]
I've been trying to keep a close eye on my two other avali and keep a backup of their save file. I'll keep in mind sending over a copy of the log if it happens again. Someone also mentioned a 'frigate mod' as causing an issue. Is that a mod that comes with the basic avali mod or others?

**Comment by Fevix** [comment]
Frigate is an addon mod that you can find in the description of the Avali's mainpage on playstarbound.

**Comment by MisterSnaivi** [comment]
This happened to me, multiple times. (rip many of my avali characters)
Here's a screenshot and my starbound log:
http://i.imgur.com/GemGNtd.png

**Comment by Fevix** [comment]
What level are you trying to upgrade to?

**Comment by MisterSnaivi** [comment]
Any level. Even fixing the thrusters/FLT Drive causes this to happen.

**Comment by Harakhti** [comment]
~~ew linux~~ judging by the log...

Could not load base image asset '/ships/avali/frigate_****OMITTED****.png'
(MaterialException) No such material id: 4277

...it's an issue with the game very particularly trying to load assets for the frigate mod.

**Comment by Fevix** [comment]
I couldn't find anything referencing material ID 4277 either, so I'm confused.

**Comment by Harakhti** [comment]
@Fevix Logistics Frigate v4.0 "has one custom block packed with release "frigatehazard.material" with a "materialId" : 4277", coming from the thread.

**Comment by Fevix** [comment]
Is this still happening?

**Comment by Fevix** [comment]
It's been almost 4 weeks since the last update to this. I'm closing it.
