### ISSUE TITLE
Bug with Non-Avali tenant spawn

### ISSUE THREAD

**Issue by Timiryazev** [Fevix/Avali#83]
With this mod installed, trying to get a Tier 5A Guard tenant results in a Tier 4 Guard instead.
I've tested with a few others, so far I haven't managed to reproduce this with anything other than the Tier 5A (other Tier 5 guards spawn fine).
Screenshot: Identical rooms (except guard type), different spawns
![guardbug](https://cloud.githubusercontent.com/assets/15707879/11016986/450ff10c-8546-11e5-9527-b3118e2884a1.png)

**Comment by thakyZ** [comment]
I believe I have fixed this but I don't know for sure someone should test it with the latest version of unstable because that should work now that I have changed how the Avali's spawn when not using Avali furniture.

**Comment by Fevix** [comment]
Please update and attempt to reproduce

**Comment by Fevix** [comment]
It's been almost 4 weeks since the last update to this. I'm closing it.
