### ISSUE TITLE
Tiered armor does not count for main quests

### ISSUE THREAD

**Issue by Jeadbe** [Fevix/Avali#99]
When asked to make a set of steel, titanium, etc. for the missions, the game doesn't recognize the Avali equivalents. Looking through the vanilla files, it seems "questTags" has changed to "itemTags"

so, for example:
"questTags" : [ "tier5armor" ],

needs to be:
"itemTags" : [ "tier5armor" ],

**Comment by Fevix** [comment]
Known issue, has been fixed in the unstable branch. Thank you for the effort, though, it's nice to see people care enough about the mod to do research like that on their own.

**Comment by Jeadbe** [comment]
looking through the github repository, those lines in the armor found in Avali/items/armors/avali/avali-tiered/ have not changed. Has this been fixed somewhere else?

**Comment by Fevix** [comment]
Forgot to actually push the commit from my local version.
